### ISSUE TITLE
how to claim the reward 

### ISSUE THREAD

**Issue by jptejj** [philipperemy/my-first-bitcoin-miner#1]
once running the code

where to claim the reward??

**Comment by philipperemy** [comment]
@jptejj it's not connected to the bitcoin network.
It's just an example to give you an idea of how the mining algorithm works with bitcoin.

**Comment by hasanfirnas** [comment]
> @jptejj it's not connected to the bitcoin network.
> It's just an example to give you an idea of how the mining algorithm works with bitcoin.

Then how to connect your code to bitcoin network

**Comment by philipperemy** [comment]
@404-ghost you can't this it's just an example. If you want to connect to the bitcoin network, go here: https://github.com/jgarzik/pyminer.

But keep in mind that you will earn close to nothing as this implementation is highly inefficient (python + CPU!).

If you want to mine, go for ASIC miners (I let you google it).
